version: '3'

services:

  angular-admin:
    build: ./_Dockerfiles/angular-admin
    stdin_open: true
    ports:
      - 4201:4200
    volumes:
      - ./angular-admin:/ai-store/angular-admin
    command:
      - /entrypoints/ai-store/angular-admin/entrypoint.sh
    links:
      - gateway

  angular-web:
    build: ./_Dockerfiles/angular-web
    stdin_open: true
    ports:
      - 4202:4200
    volumes:
      - ./angular-web:/ai-store/angular-web
    command:
      - /entrypoints/ai-store/angular-web/entrypoint.sh
    links:
      - gateway

  endpoints-main:
    build: ./_Dockerfiles/endpoints-main
    command:
      - /entrypoints/ai-store/endpoints-main/entrypoint.sh
    volumes:
      - ./endpoints-main:/ai-store/endpoints-main
    links:
      - db

  gateway:
    build: ./_Dockerfiles/gateway
    ports:
      - 85:85
    command:
      - /entrypoints/ai-store/gateway/entrypoint.sh
    volumes:
      - ./gateway:/ai-store/gateway
    links:
      - endpoints-main

  laravel-dbm:
    build: ./_Dockerfiles/laravel-dbm
    stdin_open: true
    volumes:
      - ./laravel-dbm:/var/www/laravel-dbm
    command:
      - /entrypoints/ai-store/laravel-dbm/entrypoint.sh
    links:
      - db

  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 33061:33061